# Generated by CoffeeScript 1.4.0
(->
  (->
    config = undefined
    path = undefined
    pkg = undefined
    config = undefined
    path = undefined
    pkg = undefined
    path = require("path")
    pkg = require("./package.json")
    config =
      debug: true
      name: "Node Club"
      description: "Node Club 是用 Node.js 开发的社区软件"
      version: pkg.version
      site_headers: ["<meta name=\"author\" content=\"EDP@TAOBAO\" />"]
      host: "localhost.cnodejs.org"
      google_tracker_id: "UA-41753901-5"
      site_logo: ""
      site_icon: ""
      site_navs: [[
        "/about"
        "关于"
      ]]
      site_static_host: ""
      mini_assets: false
      site_enable_search_preview: false
      site_google_search_domain: "cnodejs.org"
      upload_dir: path.join(__dirname, "public", "user_data", "images")
      db: "mongodb://127.0.0.1/node_club_dev"
      session_secret: "node_club"
      auth_cookie_name: "node_club"
      port: 3000
      list_topic_count: 20
      post_interval: 10000
      rss:
        title: "CNode：Node.js专业中文社区"
        link: "http://cnodejs.org"
        language: "zh-cn"
        description: "CNode：Node.js专业中文社区"
        max_rss_items: 50

      site_links: [
        {
          text: "Node 官方网站"
          url: "http://nodejs.org/"
        }
        {
          text: "Node Party"
          url: "http://party.cnodejs.net/"
        }
        {
          text: "Node 入门"
          url: "http://nodebeginner.org/index-zh-cn.html"
        }
        {
          text: "Node 中文文档"
          url: "http://docs.cnodejs.net/cman/"
        }
      ]
      side_ads: [
        {
          url: "http://www.upyun.com/?utm_source=nodejs&utm_medium=link&utm_campaign=upyun&md=nodejs"
          image: "http://site-cnode.b0.upaiyun.com/images/upyun_logo.png"
          text: ""
        }
        {
          url: "http://ruby-china.org/?utm_source=nodejs&utm_medium=link&utm_campaign=upyun&md=nodejs"
          image: "http://site-cnode.b0.upaiyun.com/images/ruby_china_logo.png"
          text: ""
        }
        {
          url: "http://adc.taobao.com/"
          image: "http://adc.taobao.com/bundles/devcarnival/images/d2_180x250.jpg"
          text: ""
        }
      ]
      mail_opts:
        host: "smtp.126.com"
        port: 25
        auth:
          user: "club@126.com"
          pass: "club"

      weibo_key: 10000000
      admins:
        admin: true

      plugins: []
      GITHUB_OAUTH:
        clientID: "your GITHUB_CLIENT_ID"
        clientSecret: "your GITHUB_CLIENT_SECRET"
        callbackURL: "http://cnodejs.org/auth/github/callback"

      allow_sign_up: true

    module.exports = config
    module.exports.config = config
    return
  ).call this
  return
).call this
